language: node_js
node_js:
- node
script:
- npm run test
before_deploy:
- npm run build
deploy:
  provider: npm
  email: roby.parr@gmail.com
  skip_cleanup: true
  api_key:
    secure: aAzBXeW/401waX96rfh22v3q4j9Y72h1iyetoGnGTUyP5++Q3J9ds7bDhMk70LqlY062+v0tQ2zm9NnXAd2RrQzTJk1xDmMXUNj9nXjqjl+TDFzgRavmZG5vqSyr75uWNjU5hX5D6+qnwVFmqYVvuZWIYo5IrF5PAY3MR4up4f4RbDllmPjmbTO1QL6RB89RWnjeHRIygjZtj42DzHWr9tUwCbRrBKUj2DFXlxXSoBXbzIPpbsg/XtVpurtslIvvxmuRb0DhYKeqWWVy6T0LGkARUm+ZbAnMDJ9kxa0kiLOzZdgEoqxivnx4qJvvE2wG+QrhBeKlCH0Tqs5SinOM8OHb0EFgvvAe1asPmNqXSWHLTcPkZeoHtKiDS2W3IDwj5rKElTBcIofgjXmQIRbHvY7Q8jOwnW/Qi5pREODWSVQ67ePxPfO7ciZUOKYd4BQD9X/oK13NDOw1pMiGqJBGXHF3xyVu0NPFu88or46JApKwaB9tFQC1XXyMq6UA0tZjR+xlgfpgsuwoUcu4/KyJbcZoK91x65YgPP7LUkFCrFLwf10TQEBcVFmR4DqEZ9+XYSKg+BAMzzAA+6O9kLcC+s3Ya8dpRV0YiV9MgWI95IKxuRmwHkhlZutONM//q+/RGG82zeHMpUlKtgRw6nX2/x9al747ZP6uzSr1YPRhwVc=
  on:
    tags: true
    branch: master
    repo: robyparr/elegant-editor
